### ISSUE TITLE
Release Date added for Decks

### ISSUE THREAD

**Issue by ZeldaZach** [mtgjson/mtgjson-website#154]
Should now have similar sorting options to Sets.
<img width="253" alt="Screenshot 2019-04-23 12 46 06" src="https://user-images.githubusercontent.com/7460172/56600025-d0f21700-65c5-11e9-9f94-bdabcfbe6260.png">

**Comment by staghouse** [comment]
To have the sorting options these would also need to be added to DeckLists.json which powers that downloads page.

The reason we did that is because DeckLists is more of a general overview while the Decks themselves would be (N) http requests 😱.

Can you also added them to DeckLists and I will also add the above to the IndividualDeck schema? Thanks!

**Comment by ZeldaZach** [comment]
Gotcha, working on that now

**Comment by ZeldaZach** [comment]
[DeckLists.json.txt](https://github.com/mtgjson/mtgjson-website/files/3108852/DeckLists.json.txt)

**Comment by staghouse** [comment]
Good by me if there is no `code` to also add

**Comment by ZeldaZach** [comment]
No type for now

**Comment by staghouse** [comment]
Roger. Good to go then. Will add logic to hide until its there.
