### ISSUE TITLE
Comments after recent changes (#27)

### ISSUE THREAD

**Issue by tooomm** [mtgjson/mtgjson-website#28]
Thanks for taking care of these updates, I think the page looks better now and has more complete information. 👍 

Although - after #27 - I've some comments and questions:

- Why don't we use the correct discord logo in the button, but a gamepad instead?
- In the `File Manifest`, the SET.json phrase could link to the sets page maybe?
- I would like to have something like a sub-menu at the top of the documentation with an overview of what is contained (Card, Token, Set, Keywords...). One could then click "Token" and jump to this part of the documentation directly.
- The available file extensions are named in the changelog, but they will get burried there and nobody will search for it there.
Can we have this info in the documentation as well?
Or a separate download menu point? The file manifest could go to that page too for example.
- version.json is named in the manifest, but not properly documented as all the other files. Docs should be comprehensive, even for the trivial cases :)

**Comment by ancestral** [comment]
>Why don't we use the correct discord logo in the button, but a gamepad instead?
Because our theme doesn’t support a new enough version of Font Awesome. I don’t have the time to fixing the theme or finding a new one just for this logo.

>In the File Manifest, the SET.json phrase could link to the sets page maybe?
Sounds good.

>I would like to have something like a sub-menu at the top of the documentation with an overview of what is contained (Card, Token, Set, Keywords...). One could then click "Token" and jump to this part of the documentation directly.
Hmm, that is something to ponder. I’m afraid the page would get awfully busy and considerably longer I would prefer to re-haul the whole page. This is something that I would like to do in the (not near) future.

>The available file extensions are named in the changelog, but they will get burried there and nobody will search for it there.
We’ve discussed some links on the main page and the sets page. I do agree about the need for better visibility.

>version.json is named in the manifest, but not properly documented as all the other files. Docs should be comprehensive, even for the trivial cases :)
There was a question whether metadata should be documented. (README isn’t, for example.) However, the more I think about it, I believe `version.json` probably should be mentioned.

All that being said, if you have interest in helping, I absolutely invite you join us on Discord. I would love assistance with the site.

**Comment by tooomm** [comment]
>Because our theme doesn’t support a new enough version of Font Awesome. I don’t have the time to fixing the theme or finding a new one just for this logo.

I linked https://simpleicons.org/ (CC0) in https://github.com/mtgjson/mtgjson4-website/issues/26. Is that an option?

>Hmm, that is something to ponder. I’m afraid the page would get awfully busy and considerably longer. I would prefer to re-haul the whole page. This is something that I would like to do in the (not near) future.

No idea what you've in mind... but I'm only thinking about a small navigation at the top (or next to each sub category for example):
- top
![navigation](https://user-images.githubusercontent.com/9874850/50238674-61bea900-03c0-11e9-93db-f31cced9b826.png)

- next to each category
![navigation2](https://user-images.githubusercontent.com/9874850/50238684-684d2080-03c0-11e9-999c-7f6b4afc4895.png)

Unfortunately I can't help much with coding here.

**Comment by ancestral** [comment]
Ahh, okay, something like that might be manageable. I’ll look into it, but it’ll have to be after the new year.

**Comment by ancestral** [comment]
I’m now thinking of splitting each file into its own page, which would help resolve this issue and #37.

**Comment by staghouse** [comment]
Most issues addressed in new site. See [comment](https://github.com/mtgjson/mtgjson-website/issues/9#issuecomment-463177905).
