### ISSUE TITLE
Flip night/day icon

### ISSUE THREAD

**Issue by ancestral** [mtgjson/mtgjson-website#371]
### Is your feature request related to a problem? Please describe.
When you browse the site, there’s an icon in the top right corner showing day/night mode. However, unlike other sites, like Reddit, the icon shown isn’t representative of the current mode.
### Describe the solution you'd like
Show the moon icon when in dark mode and the sun icon when in light mode.

**Comment by jroed** [comment]
When I encountered this behavior I thought it's a bug. I found it counter-intuitive.

For example [material design documentation](https://material.io/design/color/dark-theme.html#behavior) seem to recommend to show the icon for the mode that the user can activate by interacting with the element.

Maybe having a switch icon as seen in the following image would help to make the behavior clearer: https://image.shutterstock.com/image-vector/day-night-mode-switch-sun-600w-1577075101.jpg.

**Comment by ZeldaZach** [comment]
I agree with @jroed on this. I thought we were correct to begin with (having them inverted)

**Comment by staghouse** [comment]
Will defer until v5

**Comment by ancestral** [comment]
The Material Design site you linked to isn’t defining a rule — it’s just showing you an example that there can and should be a button, not what the button should look like.

[There](https://ananyaneogi.com) [are](https://stackoverflow.blog/tag/dark-mode/) [plenty](https://www.howtogeek.com/324950/how-to-activate-twitter’s-night-mode/) [of](https://www.howtogeek.com/361407/how-to-enable-dark-mode-for-youtube/) [examples](https://www.theverge.com/2018/5/25/17393320/reddit-night-mode-dark-how-to) that show the current mode, a hybrid, or a moon symbol in either state, often with a switch.

**Comment by staghouse** [comment]
Ive been mulling this over and find it quite trivial. The fact that there is multiple opinions just prove that there is no standard and thus the decisions ends up in the hands of whoever so decides.

Because of that I am going to go with the original intent which is to have the button be the state at which to enabled. In dark mode, the button is a sun with a title that says "enable light mode" and in light mode the button is a moon with a title that says "enable dark mode".
